### ISSUE TITLE
webp recording throwing an error

### ISSUE THREAD

**Issue by ozkanpakdil** [orhun/menyoki#35]
**Describe the bug**
I tried to record webp but got the error below
```
oz-mint@ozmint-MACH-WX9:~/tmp/menyoki-1.7.0$ ./menyoki record webp
[2023-03-04T13:29:22 INFO menyoki::util::command] Running the command...
[2023-03-04T13:29:22 INFO menyoki::x11::window] Starting in 3[2023-03-04T13:29:22 ERROR menyoki] IO error: `No such file or directory (os error 2)`
```

**To Reproduce**
![image](https://user-images.githubusercontent.com/604405/222906261-e655950e-a9d2-4844-89d0-932537cb8e44.png)

**System Information**
 - OS: Linux Mint 21.1 Vera 
 - Project Version: 1.7.0

**Comment by orhun** [comment]
Hello! 🐻

Recording WebP is currently not supported. You can only use `menyoki capture webp` to take screenshots.

Encoding WebP frames need to be implemented with a separate crate other than `image` since it does not support it. Something like [webp-animation](https://github.com/blaind/webp-animation) can be used I reckon.

Closing in favor of #36
